### ISSUE TITLE
Add watch task for rebuilding specRunner.html

### ISSUE THREAD

**Issue by freethejazz** [scottburch/sparrow#1]
It would be nice to have a standard watch task that rebuilds specRunner whenever specs change, then all one has to do is refresh their browser in order to run the tests again.

It may also be beneficial to add a watch task for the headless testing, but it's possible that it would cause the tests to be run _too_ frequently.

**Comment by scottburch** [comment]
Thanks for this issue.  What is the advantage of a watch task for headless testing?  I use headless testing for CI which is triggered by the CI server itself.  I don't expect people to develop using the headless runner.  They can use any other functional testing framework for that. :)

**Comment by freethejazz** [comment]
I think the headless thing should be a separate issue.

What do you think about the the headed watch task?

**Comment by scottburch** [comment]
Headed makes perfect sense.  I had thought of making a node command to do that.
